### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by Sartorra** [Sartorra/smart-taskman#2]
## Description

First time users must be able to create a user account, the user will create there account via a registration form. The data that is passed to the server must be able to ensure integrity as well as storing the information effectively creating a user account.

## TODO

- [ ] Front end Form
- [ ] Server side validation to ensure data integrity
- [ ] Store user information securely
- [ ] Login user upon successful account creation
