### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by Sartorra** [Sartorra/smart-taskman#4]
## Description

Create a way for users to sign in with there credentials, give the client a authentication token or error message in return. The server must validate the data to make sure the given credentials are correct.

## TODO
- [ ] https://github.com/Sartorra/smart-taskman/issues/3
- [ ] User Login form
- [ ] Server API Endpoint
- [ ] Validation of data
- [ ] Give the user back a token with information of the user id and expiration
