### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by Sartorra** [Sartorra/smart-taskman#7]
## Description

A system to separate data for each user of the web app.

## TODO

- [ ] https://github.com/Sartorra/smart-taskman/issues/2
- [ ] https://github.com/Sartorra/smart-taskman/issues/4
- [ ] https://github.com/Sartorra/smart-taskman/issues/5
- [ ] https://github.com/Sartorra/smart-taskman/issues/6
