### ISSUE TITLE
Smart Task List

### ISSUE THREAD

**Issue by Sartorra** [Sartorra/smart-taskman#9]
## Description
Create a list view for all smart tasks associated with a user.

## TODO
- [ ] Front end view
- [ ] API Endpoint for data requests
- [ ] Back-end handling for data
